### PR TITLE
Add copyright and smoothscroll.js

### PR DESCRIPTION
**Pull request by divyanshvinayak**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Are you going to make changes in this only?

**Comment by divyanshvinayak** [comment]
No, I think I forgot how to create another patch.

**Comment by akshat157** [comment]
smoothscroll.js was not working @divyanshvinayak. I changed the function and have added it to custom.js. Copyright text is as it is and the PR was merged therefore. Thanks!

**Comment by divyanshvinayak** [comment]
@akshat157 okay, I'm trying to fix the smoothscroll asap.

**Pull request merged**
